### ISSUE TITLE
Pygame Error After Exiting Game

### ISSUE THREAD

**Issue by Lasutriv** [Lasutriv/ProjectZ#44]
Pressing the 'ESC' key closes the game however it throws an error relating to the 'self.text_image'.
```
Traceback (most recent call last):
Game crashed or was exited.
  File "G:/Personal_Programming/Development/ProjectZ/Engine/engine.py", line 136, in <module>
    engine_main_menu.menu_new(engine_main)
  File "G:/Personal_Programming/Development/ProjectZ/Engine/engine.py", line 101, in menu_new
    self.menu_run()
  File "G:/Personal_Programming/Development/ProjectZ/Engine/engine.py", line 105, in menu_run
    self.menu_events()
  File "G:/Personal_Programming/Development/ProjectZ/Engine/engine.py", line 117, in menu_events
    button.handle_events(self.engine_main, engine_main_menu, button, event, mouse_pos)
  File "G:\Personal_Programming\Development\ProjectZ\Engine\engineLib.py", line 95, in handle_events
    self.text_image = self.font.render(self.original_text, True, self.text_color)
pygame.error: Text has zero width

Process finished with exit code 1
```

**Comment by Lasutriv** [comment]
I was prematurely exiting all pygame modules when in game, thus breaking the main menu.
